### ISSUE TITLE
翻译老文本进入死循环，不断刷屏

### ISSUE THREAD

**Issue by EXWhiteDragon** [winw1010/tataru-assistant#15]
重置缓存、重启 tataru 都没有效果

**Comment by EXWhiteDragon** [comment]
还有个问题，迄今为止 “忽略汉化文本” 都没能生效（日文、使用汉化补丁）
请问这是什么问题，我留意到就算将汉化补丁设置为繁体，繁体字也会出现在 tataru 中

最后，谢谢您的帮助！谢谢

**Comment by winw1010** [comment]
檢查中

**Comment by winw1010** [comment]
目前的版本还有死循环的问题吗? 另外忽略汉化文本的功能是将已汉化的文本原封不动地输出到Tataru中，如果你需要不显示的功能的话我之后再增加选项

**Comment by EXWhiteDragon** [comment]
> 目前的版本还有死循环的问题吗?另外忽略汉化文本的功能是将已汉化的文本原封不动地输出到Tataru中，如果你需要不显示的功能的话我之后再增加选项

似乎没有遇到了，以前出现问题时好像集中在掉线后重连，缓存可能就炸掉了。
不显示的功能您视情况添加吧！我也无所谓的，谢谢
