### ISSUE TITLE
可以在名词表中新增一些社交用语、玩家间流传的专有名词翻译吗？

### ISSUE THREAD

**Issue by EXWhiteDragon** [winw1010/tataru-assistant#16]
我在用 gpt，其实这活跟 gpt 插一句前置要求，理应就能不需要麻烦您的前提下自己 DIY 一份名词表了，但咱们是引用 API 而不是直接和 gpt 对话，所以我只能请教您了。

我是美服玩家，不了解日服有没有诸如此类的名词，所以只能提出美服的常见词汇！
**职业简写：**

- PLD: 骑士 (Paladin)
- WAR: 战士 (Warrior)
- DRK: 黑骑 (Dark Knight)
- GNB: 枪刃 (Gunbreaker)
- WHM: 白魔(White Mage)
- SCH: 学者 (Scholar)
- AST: 占星 (Astrologian)
- SGE: 贤者 (Sage)
- MNK: 武僧 (Monk)
- DRG: 龙骑 (Dragoon)
- NIN: 忍者 (Ninja)
- SAM: 武士 (Samurai)
- RPR: 镰刀 (Reaper)
- BRD: 诗人 (Bard)
- MCH: 机工士 (Machinist)
- DNC: 舞者 (Dancer)
- BLM: 黑魔 (Black Mage)
- SMN: 召唤 (Summoner)
- RDM: 赤魔 (Red Mage)
- BLU: 青魔法师 (Blue Mage)

**机制简写：**

- Chariot: 钢铁
- Dynamo: 月环

实在是太多了，我找到了一份来自 consolegameswiki 的总结，以及引用其的 bilibili 文章，如果您愿意考虑增加名词表可以翻阅:
[https://ffxiv.consolegameswiki.com/wiki/Acronyms,_abbreviations,_and_common_terms](url)
[https://www.bilibili.com/read/cv26716486/#:~:text=Raubahn%20EX](url)

**当然我也可以帮忙进行这方面工作，并将文件上传给您，毕竟是我提出的建议！但我不太清楚名词表的编辑模式**
最后再次感谢您们的工作！

**Comment by winw1010** [comment]
目前主要专注在剧情词彙的维护，这些社交用语可能之后才会加进去，在这之前你可以先使用自订翻译(下方的铅笔图示)来新增这些名词
